# flake8: noqa
# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upsf_server/protos/service_v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from upsf_server.protos import (
    messages_v1_pb2 as upsf__server_dot_protos_dot_messages__v1__pb2,
)
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#upsf_server/protos/service_v1.proto\x12\x15wt474_upsf_service.v1\x1a$upsf_server/protos/messages_v1.proto\x1a\x1egoogle/protobuf/wrappers.proto"\xa6\x02\n\tUpdateReq\x12%\n\x04item\x18\x01 \x01(\x0b\x32\x17.wt474_messages.v1.Item\x12\x46\n\x0eupdate_options\x18\x02 \x01(\x0b\x32..wt474_upsf_service.v1.UpdateReq.UpdateOptions\x1a\xa9\x01\n\rUpdateOptions\x12]\n\x13list_merge_strategy\x18\x01 \x01(\x0e\x32@.wt474_upsf_service.v1.UpdateReq.UpdateOptions.ListMergeStrategy"9\n\x11ListMergeStrategy\x12\t\n\x05union\x10\x00\x12\x0b\n\x07replace\x10\x01\x12\x0c\n\x08subtract\x10\x02"\xd9\x01\n\x07ReadReq\x12\x31\n\x08itemtype\x18\x01 \x03(\x0e\x32\x1f.wt474_upsf_service.v1.ItemType\x12\x32\n\titemstate\x18\x02 \x03(\x0e\x32\x1f.wt474_messages.v1.DerivedState\x12,\n\x06parent\x18\x03 \x03(\x0b\x32\x1c.google.protobuf.StringValue\x12*\n\x04name\x18\x04 \x03(\x0b\x32\x1c.google.protobuf.StringValue\x12\r\n\x05watch\x18\x05 \x01(\x08*\x96\x01\n\x08ItemType\x12\x13\n\x0fservice_gateway\x10\x00\x12\x1e\n\x1aservice_gateway_user_plane\x10\x01\x12\x1d\n\x19traffic_steering_function\x10\x02\x12\x16\n\x12network_connection\x10\x03\x12\t\n\x05shard\x10\x04\x12\x13\n\x0fsession_context\x10\x05\x32\xf9\x02\n\x04upsf\x12>\n\x08\x43reateV1\x12\x17.wt474_messages.v1.Item\x1a\x17.wt474_messages.v1.Item"\x00\x12\x45\n\x06ReadV1\x12\x1e.wt474_upsf_service.v1.ReadReq\x1a\x17.wt474_messages.v1.Item"\x00\x30\x01\x12G\n\x08UpdateV1\x12 .wt474_upsf_service.v1.UpdateReq\x1a\x17.wt474_messages.v1.Item"\x00\x12H\n\x08\x44\x65leteV1\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValue"\x00\x12W\n\x08LookupV1\x12&.wt474_messages.v1.SessionContext.Spec\x1a!.wt474_messages.v1.SessionContext"\x00\x62\x06proto3'
)

_ITEMTYPE = DESCRIPTOR.enum_types_by_name["ItemType"]
ItemType = enum_type_wrapper.EnumTypeWrapper(_ITEMTYPE)
service_gateway = 0
service_gateway_user_plane = 1
traffic_steering_function = 2
network_connection = 3
shard = 4
session_context = 5


_UPDATEREQ = DESCRIPTOR.message_types_by_name["UpdateReq"]
_UPDATEREQ_UPDATEOPTIONS = _UPDATEREQ.nested_types_by_name["UpdateOptions"]
_READREQ = DESCRIPTOR.message_types_by_name["ReadReq"]
_UPDATEREQ_UPDATEOPTIONS_LISTMERGESTRATEGY = (
    _UPDATEREQ_UPDATEOPTIONS.enum_types_by_name["ListMergeStrategy"]
)
UpdateReq = _reflection.GeneratedProtocolMessageType(
    "UpdateReq",
    (_message.Message,),
    {
        "UpdateOptions": _reflection.GeneratedProtocolMessageType(
            "UpdateOptions",
            (_message.Message,),
            {
                "DESCRIPTOR": _UPDATEREQ_UPDATEOPTIONS,
                "__module__": "upsf_server.protos.service_v1_pb2"
                # @@protoc_insertion_point(class_scope:wt474_upsf_service.v1.UpdateReq.UpdateOptions)
            },
        ),
        "DESCRIPTOR": _UPDATEREQ,
        "__module__": "upsf_server.protos.service_v1_pb2"
        # @@protoc_insertion_point(class_scope:wt474_upsf_service.v1.UpdateReq)
    },
)
_sym_db.RegisterMessage(UpdateReq)
_sym_db.RegisterMessage(UpdateReq.UpdateOptions)

ReadReq = _reflection.GeneratedProtocolMessageType(
    "ReadReq",
    (_message.Message,),
    {
        "DESCRIPTOR": _READREQ,
        "__module__": "upsf_server.protos.service_v1_pb2"
        # @@protoc_insertion_point(class_scope:wt474_upsf_service.v1.ReadReq)
    },
)
_sym_db.RegisterMessage(ReadReq)

_UPSF = DESCRIPTOR.services_by_name["upsf"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _ITEMTYPE._serialized_start = 650
    _ITEMTYPE._serialized_end = 800
    _UPDATEREQ._serialized_start = 133
    _UPDATEREQ._serialized_end = 427
    _UPDATEREQ_UPDATEOPTIONS._serialized_start = 258
    _UPDATEREQ_UPDATEOPTIONS._serialized_end = 427
    _UPDATEREQ_UPDATEOPTIONS_LISTMERGESTRATEGY._serialized_start = 370
    _UPDATEREQ_UPDATEOPTIONS_LISTMERGESTRATEGY._serialized_end = 427
    _READREQ._serialized_start = 430
    _READREQ._serialized_end = 647
    _UPSF._serialized_start = 803
    _UPSF._serialized_end = 1180
# @@protoc_insertion_point(module_scope)
